### ISSUE TITLE
Difference between SE3Quat and Isometry3D

### ISSUE THREAD

**Issue by ylmzkaan** [RainerKuemmerle/g2o#417]
I generally represent my rigid transformations with an Isometry3d object. But I know that the graph representation of g2o uses SE3 to represent a transformation quite a lot. Both Isometry3d and SE3quat seems to apply a translation and 3D rotation to a given entity. Can someone explain what is the difference between the two?

**Comment by RainerKuemmerle** [comment]
Earlier there was SE3Quat used in the 3D SLAM types but since wuite a while we have, for instance
`class G2O_TYPES_SLAM3D_API VertexSE3 : public BaseVertex<6, Isometry3>`

Both, SE3Quat and Isometry3 represent a member of SE3 while one uses a quaternion and the other uses a matrix to represent the rotation. Apart of thet the user should not note much of a difference.
