### ISSUE TITLE
Object ownership

### ISSUE THREAD

**Issue by vahagnIV** [RainerKuemmerle/g2o#499]
I am writing a SLAM program that constantly runs various BA tasks using g2o. Hence, I decided to keep the optimizable points and Euclidean transformations in g2o objects  (i.e. VertextPointXYZ and VertexSE3Expmap ) so that I can directly add them to the optimizer and use them right after the optimization is finished. However, the SparseOptimizer ( never checked any other ) destroys all vertices and edges that were added to it in the destructor. Is there a way to tell it that it should destroy only edges or do not destroy anything at all?

**Comment by RainerKuemmerle** [comment]
You can set the compile option G2O_NO_IMPLICIT_OWNERSHIP_OF_OBJECTS to manage on your own.
However, it is typically more efficient to also keep the sparse optimizer alive instead of in each cycle re-create a new one.

I started a branch using shared_ptr, see https://github.com/RainerKuemmerle/g2o/tree/memory_management that also addresses this as we would change the API to have shared pointer and it should also allow the use case you described.But it is work in progress, and might need tweaks and tests to verify bookkeeping.

**Comment by vahagnIV** [comment]
Thanks
