### ISSUE TITLE
[build error] 

### ISSUE THREAD

**Issue by Ever-Bright-V** [RainerKuemmerle/g2o#792]
[ 43%] Generating ui_base_properties_widget.h
/home/everbright/anaconda3/bin/uic: error while loading shared libraries: libicui18n.so.58: cannot open shared object file: No such file or directory
make[2]: *** [g2o/apps/g2o_viewer/CMakeFiles/viewer_library.dir/build.make:78：g2o/apps/g2o_viewer/ui_base_properties_widget.h] 错误 127
make[1]: *** [CMakeFiles/Makefile2:1357：g2o/apps/g2o_viewer/CMakeFiles/viewer_library.dir/all] 错误 2
make: *** [Makefile:156：all] 错误 2

**Comment by RainerKuemmerle** [comment]
Probably broken anaconda installation. uic (User Interface Compiler) is part of Qt and yours does not seem to be correctly executable. This is in the first place not something to be fixed in g2o itself.
Please let me know there is something in g2o's build setup to better support anaconda in general.
